name: Build Forked OpenWrt Snapshot
run-name: Build OpenWrt ${{ github.event.inputs.subtarget }}-${{ github.event.inputs.profile }}
on:
  workflow_dispatch:
    inputs:
      target:
        description: Target
        required: true
        default: qualcommbe
      subtarget:
        description: Subtarget
        required: true
        default: ipq95xx
      profile:
        description: Device Profile
        required: true
        default: askey_sbe1v1k

jobs:
  pre-config:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout FORKED OpenWrt source
        uses: actions/checkout@v4
        with:
          path: openwrt
          fetch-depth: 0

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses-dev gawk flex bison openssl libssl-dev \
          dkms libelf-dev libudev-dev libpci-dev libiberty-dev autoconf automake \
          git wget curl rsync unzip python3 python3-pip

      - name: Update & Install Feeds
        working-directory: ./openwrt
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate .config
        working-directory: ./openwrt
        run: |
          rm -f .config
          echo "CONFIG_TARGET_${{ github.event.inputs.target }}=y" >> .config
          echo "CONFIG_TARGET_${{ github.event.inputs.target }}_${{ github.event.inputs.subtarget }}=y" >> .config
          echo "CONFIG_TARGET_${{ github.event.inputs.target }}_${{ github.event.inputs.subtarget }}_DEVICE_${{ github.event.inputs.profile }}=y" >> .config
          make defconfig
 
      - name: Upload .config as artifact
        uses: actions/upload-artifact@v4
        working-directory: ./openwrt
        with:
          name: openwrt-config
          path: openwrt/.config

  build-fw:
    needs: pre-config
    environment: check-config
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout OpenWrt fork
        uses: actions/checkout@v4
        with:
          path: openwrt
          fetch-depth: 0

      - name: Download .config artifact
        uses: actions/download-artifact@v4
        working-directory: ./openwrt
        with:
          name: openwrt-config
          path: openwrt/

      - name: Download source files
        working-directory: ./openwrt
        run: make download -j$(nproc)

      - name: Compile firmware
        working-directory: ./openwrt
        run: make -j$(nproc) || make -j1 V=s

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-${{ github.event.inputs.target }}-${{ github.event.inputs.subtarget }}-${{ github.event.inputs.profile }}
          path: openwrt/bin/targets/**
