name: Build Forked OpenWrt Snapshot
run-name: Build OpenWrt ${{ github.event.inputs.subtarget }}-${{ github.event.inputs.profile }}

on:
  workflow_dispatch:
    inputs:
      target:
        description: qualcommbe
        required: true
        default: qualcommbe
      subtarget:
        description: ipq95xx
        required: true
        default: qualcommbe_ipq95xx
      profile:
        description: qualcommbe_ipq95xx_DEVICE_askey_sbe1v1k
        required: true
        default: askey_sbe1v1k
  # push:
  #   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout FORKED OpenWrt source
        uses: actions/checkout@v4
        with:
          path: openwrt
          fetch-depth: 0

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses-dev gawk flex bison openssl libssl-dev \
          dkms libelf-dev libudev-dev libpci-dev libiberty-dev autoconf automake \
          git wget curl rsync unzip python3 python3-pip

      - name: Update & Install Feeds
        working-directory: ./openwrt
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate .config
        working-directory: ./openwrt
        run: |
          make defconfig
          echo "CONFIG_TARGET_${{ github.event.inputs.target }}=${{ github.event.inputs.subtarget }}=y" >> .config
          echo "CONFIG_TARGET_${{ github.event.inputs.target }}_${{ github.event.inputs.subtarget }}_PROFILE_${{ github.event.inputs.profile }}=y" >> .config
          make defconfig

      - name: Download source files
        working-directory: ./openwrt
        run: make download -j$(nproc)

      - name: Compile firmware
        working-directory: ./openwrt
        run: make -j$(nproc) || make -j1 V=s

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-${{ github.event.inputs.target }}-${{ github.event.inputs.subtarget }}-${{ github.event.inputs.profile }}
          path: openwrt/bin/targets/**
