name: Build SBE1V1K IPQ95xx OpenWrt
on:
  push:
    branches: [ clean-main ]
  workflow_dispatch: # 手动触发

env:
  TARGET_PROFILE: qualcommbe_ipq95xx
  TARGET_ARCH: aarch64_cortex-a53
  BUILD_ROOT: ${{ github.workspace }}
  CCACHE_DIR: ${{ github.workspace }}/ccache

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo sun9999-dev/SBE1V1K-OpenWrt
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true

      - name: Install build dependencies (Ubuntu24.04 修复distutils)
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
          python3 python3-setuptools rsync swig unzip zlib1g-dev file wget libelf-dev

      - name: Restore cache (dl + build_dir + staging_dir + ccache)
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.BUILD_ROOT }}/dl
            ${{ env.BUILD_ROOT }}/build_dir
            ${{ env.BUILD_ROOT }}/staging_dir
            ${{ env.CCACHE_DIR }}
          key: ${{ runner.os }}-sbe1v1k-openwrt-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-sbe1v1k-openwrt-

      - name: Prepare build env & ccache
        run: |
          echo "export CCACHE_DIR=${{ env.CCACHE_DIR }}" >> ~/.bashrc
          echo "export PATH=/usr/lib/ccache:$PATH" >> ~/.bashrc
          source ~/.bashrc
          ccache -M 5G
          ccache -s

      - name: Update feeds & defconfig
        run: |
          # 清华镜像加速feeds源码
          sed -i 's#https://git.openwrt.org#https://mirrors.tuna.tsinghua.edu.cn/git/openwrt#g' feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          cp .config .config.old
          make defconfig

      - name: Incremental compile (仅打包bin产物)
        run: |
          # 首次全新编译取消下面注释，注释 package/compile
          # make -j$(nproc)
          make package/compile -j$(nproc)
          make target/image -j$(nproc)
          make package/index

      - name: Print final vermagic (校验内核hash)
        run: |
          cat build_dir/target-${{ env.TARGET_ARCH }}/linux-${{ env.TARGET_PROFILE }}/linux-6.18.39/.vermagic

      - name: Package firmware & packages
        run: |
          tar -zcvf firmware.tar.gz bin/target/${{ env.TARGET_PROFILE }}
          tar -zcvf packages.tar.gz bin/packages/${{ env.TARGET_ARCH }}

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-sbe1v1k-firmware
          path: ${{ env.BUILD_ROOT }}/firmware.tar.gz
          retention-days: 7

      - name: Upload packages repo artifact
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-sbe1v1k-packages
          path: ${{ env.BUILD_ROOT }}/packages.tar.gz
          retention-days: 7
